[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qecsim"
version = "0.1.0"
description = "Quantum error correction and lattice surgery tools"
readme = "README.md"
requires-python = ">=3.10"

# dependencies
dependencies = [
    "numpy>=1.24",
    "pymatching>=2.0",
    "tqecd>=0.1.2",
    "cvxpy>=1.7.3",
    "ecos>=2.0",
    "stim>=1.12",
    "sinter>=1.15.0"
]

[[project.authors]]
name = "Fabian Spreemann"
email = "f.spreemann@fz-juelich.de"

[tool.setuptools.packages.find]
where = ["."]
include = ["qecsim*"]

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
    ".venv",
    ".ruff_cache",
    ".pytest_cache",
    "playground",
    "qecsim.egg-info",
    "*.ipynb",
    "**/*.ipynb",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "UP", "N", "ARG", "COM", "ISC", "Q"]
ignore = ["W291", "W293"]

[tool.ruff.lint.isort]
known-first-party = ["qecsim"]
combine-as-imports = true